[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_CDC_ON_BOOT=1
  -I${PROJECT_INCLUDE_DIR}

extra_scripts =
  pre:scripts/patch_gfx_library.py

lib_deps =
  moononournation/GFX Library for Arduino@^1.5.1
  bblanchon/ArduinoJson @ ^7.0.0
