"""Generate Korean female TTS clips as C headers of 16-bit PCM samples.

Each entry in CLIPS produces include/assets/<name>_pcm.h, each defining
    <NAME>_PCM_SAMPLE_RATE
    <NAME>_PCM_SAMPLES
    <NAME>_PCM[]

Regenerate with:
    python scripts/gen_greeting_tts.py
"""
import asyncio
import os

import edge_tts
import miniaudio

VOICE     = "ko-KR-SunHiNeural"     # Korean female
TARGET_SR = 24000                   # matches AudioManager I2S
PEAK      = 28000                   # normalization peak (headroom below int16 max 32767)

CLIPS = [
    # (stem, text) — switch announcement is composed at runtime as:
    #   num_<N> + state_on/off   →   "N번 스위치가 켜/꺼졌습니다."
    ("greeting",  "안녕하세요. 슬라워입니다."),
    ("num_1",     "일번,"),    # Sino-Korean reading (not 한번)
    ("num_2",     "이번,"),    # Sino-Korean reading (not 두번)
    ("num_3",     "삼번,"),    # Sino-Korean reading (not 세번)
    ("state_on",  "스위치가 켜졌습니다."),
    ("state_off", "스위치가 꺼졌습니다."),
    ("temp_high", "온도가 높아요."),
]

THIS_DIR   = os.path.dirname(os.path.abspath(__file__))
PROJECT    = os.path.dirname(THIS_DIR)
ASSETS_DIR = os.path.join(THIS_DIR, "assets")
HEADER_DIR = os.path.join(PROJECT, "include", "assets")


async def synthesize_one(text, mp3_path):
    comm = edge_tts.Communicate(text, VOICE)
    with open(mp3_path, "wb") as f:
        async for chunk in comm.stream():
            if chunk["type"] == "audio":
                f.write(chunk["data"])


def decode_and_process(mp3_path):
    decoded = miniaudio.decode_file(
        mp3_path,
        output_format=miniaudio.SampleFormat.SIGNED16,
        nchannels=1,
        sample_rate=TARGET_SR,
    )
    samples = list(decoded.samples)
    raw_n = len(samples)

    # Trim leading/trailing silence — tight pad so concatenated clips
    # don't produce awkward gaps when composed at runtime.
    THRESH = 200
    PAD = int(TARGET_SR * 0.02)   # 20 ms
    first = next((i for i, s in enumerate(samples) if abs(s) > THRESH), 0)
    last  = next((i for i, s in enumerate(reversed(samples)) if abs(s) > THRESH), 0)
    first = max(0, first - PAD)
    last  = max(0, last  - PAD)
    samples = samples[first : len(samples) - last]

    # Normalize to target peak
    peak = max((abs(s) for s in samples), default=1)
    if peak > 0:
        gain = PEAK / peak
        samples = [max(-32768, min(32767, int(s * gain))) for s in samples]
    return samples, raw_n, peak


def emit_header(stem, text, samples):
    name = stem.upper()
    path = os.path.join(HEADER_DIR, f"{stem}_pcm.h")
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "// Auto-generated by scripts/gen_greeting_tts.py\n"
            f"// Source text: {text}\n"
            f"// Voice: {VOICE}\n"
            f"// Format: 24 kHz, 16-bit signed PCM, mono, normalized to +-{PEAK}\n"
            "#pragma once\n"
            "#include <stdint.h>\n"
            "#include <stddef.h>\n\n"
            f"static constexpr uint32_t {name}_PCM_SAMPLE_RATE = {TARGET_SR};\n"
            f"static constexpr size_t   {name}_PCM_SAMPLES     = {len(samples)};\n"
            f"static const int16_t {name}_PCM[] = {{\n"
        )
        line = []
        for s in samples:
            line.append(f"{s:6d}")
            if len(line) == 12:
                f.write("  " + ",".join(line) + ",\n")
                line = []
        if line:
            f.write("  " + ",".join(line) + "\n")
        f.write("};\n")


async def main():
    os.makedirs(ASSETS_DIR, exist_ok=True)
    os.makedirs(HEADER_DIR, exist_ok=True)

    for stem, text in CLIPS:
        mp3 = os.path.join(ASSETS_DIR, f"{stem}.mp3")
        await synthesize_one(text, mp3)
        samples, raw_n, peak = decode_and_process(mp3)
        emit_header(stem, text, samples)
        print(f"{stem:10s}  raw={raw_n:6d}  trim={len(samples):6d}  "
              f"dur={len(samples)/TARGET_SR:.2f}s  peak={peak}")


if __name__ == "__main__":
    asyncio.run(main())
